-- Auto-generated from schema-map-postgres.yaml (map@sha1:8C4F2BC1C4D22EE71E27B5A7968C71E32D8D884D)
-- engine: postgres
-- table:  sync_batches

CREATE TABLE IF NOT EXISTS sync_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel VARCHAR(120) NOT NULL,
  producer_peer_id BIGINT NOT NULL,
  consumer_peer_id BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  items_total INTEGER NOT NULL DEFAULT 0,
  items_ok    INTEGER NOT NULL DEFAULT 0,
  items_failed INTEGER NOT NULL DEFAULT 0,
  error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  started_at  TIMESTAMPTZ(6) NULL,
  finished_at TIMESTAMPTZ(6) NULL,
  CONSTRAINT chk_sync_batches_status CHECK (status IN ('pending','sending','completed','failed','cancelled'))
);
